
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author taniasafavi
 */
public class OrderSystem extends javax.swing.JFrame {

    /**
     * Creates new form OrderSystem
     */
    public OrderSystem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tPizzaNamn = new javax.swing.JComboBox();
        tStorlek = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jNästa = new javax.swing.JButton();
        jAvbryt = new javax.swing.JButton();
        jLäggaTill = new javax.swing.JToggleButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblProduct = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        tAntal = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PIZZA ORDER SYSTEM");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 10, 240, 32);

        jLabel6.setText("Kostnad: ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 200, 70, 20);

        jLabel3.setText("Pizza Namn:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 116, 77, 30);

        jLabel4.setText("Storlek:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 160, 50, 20);

        tPizzaNamn.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Margherita", "Al Funghi", "Capricciosa", "Pepperoni" }));
        getContentPane().add(tPizzaNamn);
        tPizzaNamn.setBounds(160, 117, 120, 30);

        tStorlek.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Normal", "Familj", "Barn" }));
        tStorlek.setToolTipText("");
        tStorlek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tStorlekActionPerformed(evt);
            }
        });
        getContentPane().add(tStorlek);
        tStorlek.setBounds(160, 150, 120, 40);

        jLabel9.setFont(new java.awt.Font("Hiragino Kaku Gothic StdN", 0, 18)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon("/Users/taniasafavi/Desktop/Supreme_pizza.jpg")); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(100, 0, 340, 60);

        jNästa.setText("Nästa");
        jNästa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNästaActionPerformed(evt);
            }
        });
        getContentPane().add(jNästa);
        jNästa.setBounds(150, 250, 80, 29);

        jAvbryt.setText("Avbryt");
        getContentPane().add(jAvbryt);
        jAvbryt.setBounds(250, 250, 97, 29);

        jLäggaTill.setText("Lägga till");
        jLäggaTill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLäggaTillActionPerformed(evt);
            }
        });
        getContentPane().add(jLäggaTill);
        jLäggaTill.setBounds(40, 250, 100, 29);

        tblProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pizza namn", "Storlek", "Antal", "Kostnad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblProduct);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(30, 300, 450, 100);

        jLabel2.setText("Order ID: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(420, 80, 70, 16);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(480, 80, 40, 20);

        tAntal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));
        getContentPane().add(tAntal);
        tAntal.setBounds(340, 150, 60, 27);

        jLabel5.setText("Antal:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(300, 150, 40, 30);

        jTextField2.setText("jTextField2");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(160, 200, 110, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tStorlekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tStorlekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tStorlekActionPerformed

    private void jNästaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNästaActionPerformed


    }//GEN-LAST:event_jNästaActionPerformed

    private void jLäggaTillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLäggaTillActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblProduct.getModel();
        model.addRow(new Object[]{tPizzaNamn.getSelectedItem(),tStorlek.getSelectedItem().toString(),tAntal.getSelectedItem()} );

    }//GEN-LAST:event_jLäggaTillActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAvbryt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToggleButton jLäggaTill;
    private javax.swing.JButton jNästa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JComboBox tAntal;
    private javax.swing.JComboBox tPizzaNamn;
    private javax.swing.JComboBox tStorlek;
    private javax.swing.JTable tblProduct;
    // End of variables declaration//GEN-END:variables
}
